### ISSUE TITLE
[BUG] First load of a playlist

### ISSUE THREAD

**Issue by icepick4** [s-rigaud/huskyfy#83]
Hello!

I got an issue when I load for the first time a playlist, no matter if its more than 150 tracks or less the counter stays at 0.

I have to reload the page to have the counter, its a detail but it could great to fix it.

**Comment by s-rigaud** [comment]
Hi 👋 
Problem should be solved and a number scrolling animation should appear for not previously loaded playlists. Tell me if you still have the issue 🤔

**Comment by icepick4** [comment]
No more issue well done !
